version: '3.7'
services:
 Cloud2020-88732:
  image: mysql:5
  environment:
   MYSQL_ROOT_USER: DKrol
   MYSQL_ROOT_PASSWORD: password
   MYSQL_USER: DKrol
   MYSQL_PASSWORD: password
   MYSQL_DATABASE: baza
  container_name: Cloud2020-88732
  networks:
   Bridge-Zadanie-1:
    ipv4_address: 10.0.10.3
  expose:
   - 3306
 java:
  image: dakr0/lab9_java
  restart: on-failure
  depends_on:
   - Cloud2020-88732
  networks:
   - Bridge-Zadanie-1
  stdin_open: true
  tty: true
networks:
 Bridge-Zadanie-1:
  driver: bridge
  ipam:
   config:
    - subnet: 10.0.10.0/24
